"""added last synced in leetcode contest codeforces profile and codeforces contest table

Revision ID: 13a3403d70d6
Revises: 722624549c87
Create Date: 2026-06-20 00:20:45.405579

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '13a3403d70d6'
down_revision: Union[str, Sequence[str], None] = '722624549c87'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeforcescontest', sa.Column('last_synced', sa.Date(), nullable=True))
    op.add_column('codeforcesprofile', sa.Column('last_synced', sa.Date(), nullable=True))
    op.add_column('leetcodecontest', sa.Column('last_synced', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leetcodecontest', 'last_synced')
    op.drop_column('codeforcesprofile', 'last_synced')
    op.drop_column('codeforcescontest', 'last_synced')
    # ### end Alembic commands ###
