"""added last submission id attribute in codeforcesprofile table

Revision ID: 3a7ebdab516c
Revises: 84211264b2d4
Create Date: 2026-06-23 02:14:30.812294

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3a7ebdab516c'
down_revision: Union[str, Sequence[str], None] = '84211264b2d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeforcescontest', sa.Column('last_submission_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codeforcescontest', 'last_submission_id')
    # ### end Alembic commands ###
