"""added last synced in leetcode profile table

Revision ID: 722624549c87
Revises: eb385b7ed7db
Create Date: 2026-06-19 23:37:15.265821

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '722624549c87'
down_revision: Union[str, Sequence[str], None] = 'eb385b7ed7db'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leetcodeprofile', sa.Column('last_synced', sa.Date(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leetcodeprofile', 'last_synced')
    # ### end Alembic commands ###
