"""added streaks attribute in codeforces profile table

Revision ID: 84211264b2d4
Revises: 13a3403d70d6
Create Date: 2026-06-22 23:40:47.030308

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '84211264b2d4'
down_revision: Union[str, Sequence[str], None] = '13a3403d70d6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('codeforcesprofile', sa.Column('current_streak', sa.Integer(), nullable=True))
    op.add_column('codeforcesprofile', sa.Column('current_year_longest_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codeforcesprofile', 'current_year_longest_streak')
    op.drop_column('codeforcesprofile', 'current_streak')
    # ### end Alembic commands ###
