"""added codeforces contest table

Revision ID: 992ed2b71233
Revises: c20e8a6a5293
Create Date: 2026-06-19 13:57:19.386758

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '992ed2b71233'
down_revision: Union[str, Sequence[str], None] = 'c20e8a6a5293'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('codeforcescontest',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('contest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rank', sa.Integer(), nullable=True),
    sa.Column('old_rating', sa.Integer(), nullable=True),
    sa.Column('new_rating', sa.Integer(), nullable=True),
    sa.Column('contest_date', sa.DateTime(), nullable=True),
    sa.Column('contest_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('codeforcescontest')
    # ### end Alembic commands ###
