"""added leetcode contest table

Revision ID: c20e8a6a5293
Revises: f3cc3f6b35eb
Create Date: 2026-06-18 17:46:03.264508

"""
from typing import Sequence, Union
import sqlmodel
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c20e8a6a5293'
down_revision: Union[str, Sequence[str], None] = 'f3cc3f6b35eb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('leetcodecontest',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('contest_name', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('problems_solved', sa.Integer(), nullable=True),
    sa.Column('total_problems', sa.Integer(), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('finishTime', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leetcodecontest')
    # ### end Alembic commands ###
