"""added max streak and current streak in leetcode profile table

Revision ID: e441afe22cf8
Revises: 992ed2b71233
Create Date: 2026-06-19 21:03:43.182002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e441afe22cf8'
down_revision: Union[str, Sequence[str], None] = '992ed2b71233'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leetcodeprofile', sa.Column('max_streak', sa.Integer(), nullable=True))
    op.add_column('leetcodeprofile', sa.Column('current_streak', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('leetcodeprofile', 'current_streak')
    op.drop_column('leetcodeprofile', 'max_streak')
    # ### end Alembic commands ###
