"""change max streak attribute of leetcode profile table to max streak current year

Revision ID: eb385b7ed7db
Revises: e441afe22cf8
Create Date: 2026-06-19 21:17:47.142480

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'eb385b7ed7db'
down_revision: Union[str, Sequence[str], None] = 'e441afe22cf8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leetcodeprofile', sa.Column('max_streak_current_year', sa.Integer(), nullable=True))
    op.drop_column('leetcodeprofile', 'max_streak')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('leetcodeprofile', sa.Column('max_streak', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('leetcodeprofile', 'max_streak_current_year')
    # ### end Alembic commands ###
