"""rectified the wrong assignment

Revision ID: ed2fd933c3aa
Revises: 3a7ebdab516c
Create Date: 2026-06-23 02:16:16.488382

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ed2fd933c3aa'
down_revision: Union[str, Sequence[str], None] = '3a7ebdab516c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codeforcescontest', 'last_submission_id')
    op.add_column('codeforcesprofile', sa.Column('last_submission_id', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('codeforcesprofile', 'last_submission_id')
    op.add_column('codeforcescontest', sa.Column('last_submission_id', sa.INTEGER(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
