"""database migration from sqlite to postgres

Revision ID: f3cc3f6b35eb
Revises: f6ccc53a68f4
Create Date: 2026-06-17 23:08:46.750421

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f3cc3f6b35eb'
down_revision: Union[str, Sequence[str], None] = 'f6ccc53a68f4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
