"""setting up database initially

Revision ID: f6ccc53a68f4
Revises: 
Create Date: 2026-06-17 00:34:09.094764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'f6ccc53a68f4'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('isActive', sa.Boolean(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('hashed_password', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('leetcode_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('codeforces_handle', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_codeforces_handle'), 'user', ['codeforces_handle'], unique=False)
    op.create_index(op.f('ix_user_leetcode_handle'), 'user', ['leetcode_handle'], unique=False)
    op.create_index(op.f('ix_user_username'), 'user', ['username'], unique=True)
    op.create_table('codeforcesprofile',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('firstname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('lastname', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('rating', sa.Integer(), nullable=True),
    sa.Column('max_rating', sa.Integer(), nullable=True),
    sa.Column('rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('max_rank', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('country', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('friendsCount', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('leetcodeprofile',
    sa.Column('user_id', sa.Uuid(), nullable=False),
    sa.Column('solved_problems', sa.Integer(), nullable=True),
    sa.Column('hard_solved_problems', sa.Integer(), nullable=True),
    sa.Column('medium_solved_problems', sa.Integer(), nullable=True),
    sa.Column('easy_solved_problems', sa.Integer(), nullable=True),
    sa.Column('unsolved_problems', sa.Integer(), nullable=True),
    sa.Column('ranking', sa.Integer(), nullable=True),
    sa.Column('contest_count', sa.Integer(), nullable=True),
    sa.Column('contest_rating', sa.Integer(), nullable=True),
    sa.Column('contest_ranking', sa.Integer(), nullable=True),
    sa.Column('contest_percentage', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('leetcodeprofile')
    op.drop_table('codeforcesprofile')
    op.drop_index(op.f('ix_user_username'), table_name='user')
    op.drop_index(op.f('ix_user_leetcode_handle'), table_name='user')
    op.drop_index(op.f('ix_user_codeforces_handle'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
